"""empty message

Revision ID: e69c50b4c372
Revises: 4f3640f96819
Create Date: 2019-05-02 15:57:10.721904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e69c50b4c372'
down_revision = '4f3640f96819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('ticket_type', sa.Column('open_at', sa.DateTime(), nullable=False))
    op.alter_column('user', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ticket_type', 'open_at')
    op.alter_column('event', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
